# Generated by Django 5.2.14 on 2026-05-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organizerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_banners/'),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='org_type',
            field=models.CharField(blank=True, help_text='e.g. Non-profit, Educational, Corporate', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
