# Generated by Django 5.2.14 on 2026-05-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organizerprofile_total_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='org_type',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='total_followers',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='total_hosted_events',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='organizerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_events_attended',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='org_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated interests'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer'), ('speaker', 'Speaker')], default='attendee', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
