# Generated by Django 5.2.14 on 2026-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organizerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='organizer_covers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
