# Generated by Django 5.2.14 on 2026-05-30 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_cover_photo'),
        ('events', '0009_category_eventanalytics_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='total_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='total_hosted_events',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_events_attended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='org_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('attendee', 'Attendee'), ('organizer', 'Organizer'), ('admin', 'Admin')], db_index=True, default='attendee', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('location_tracking', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interested_categories', models.ManyToManyField(blank=True, to='events.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
