# Generated by Django 5.2.14 on 2026-05-30 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_reportedevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EventAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('platform', models.CharField(default='web', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NPR', max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='total_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No Show')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together={('user', 'event')},
        ),
        migrations.AddIndex(
            model_name='eventcomment',
            index=models.Index(fields=['event', 'created_at'], name='events_even_event_i_e65645_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlike',
            index=models.Index(fields=['event', 'created_at'], name='events_even_event_i_5b2952_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='events_noti_user_id_c9a7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status', 'registered_at'], name='events_regi_status_2f3eff_idx'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start_date'], name='events_even_status_dfba18_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['city', 'category'], name='events_even_city_222640_idx'),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='events.registration'),
        ),
        migrations.AddIndex(
            model_name='eventanalytics',
            index=models.Index(fields=['event', 'action', 'created_at'], name='events_even_event_i_70031a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventanalytics',
            index=models.Index(fields=['created_at'], name='events_even_created_ea1ecc_idx'),
        ),
    ]
