# Generated by Django 5.2.14 on 2026-05-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_joining_instructions_event_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
