# Generated by Django 5.2.14 on 2026-05-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_payment_payment_method_payment_transaction_uuid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
    ]
