# Generated by Django 5.2.14 on 2026-05-30 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_category_eventanalytics_payment_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_city_222640_idx',
            old_name='events_even_city_44aff2_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category'),
        ),
    ]
