# Generated by Django 5.2.14 on 2026-05-31 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_organizerprofile_address_and_more'),
        ('events', '0010_rename_events_even_city_44aff2_idx_events_even_city_222640_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('hackathon', 'Hackathon'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('networking', 'Networking'), ('other', 'Other')], default='conference', max_length=50),
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_status_dfba18_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_city_222640_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventcomment',
            name='events_even_event_i_e65645_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventlike',
            name='events_even_event_i_5b2952_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='events_noti_user_id_c9a7f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='events_regi_status_2f3eff_idx',
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='popularity_score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_bookings',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In')], default='confirmed', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='eventlike',
            unique_together={('event', 'user')},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EventAnalytics',
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='ReportedEvent',
        ),
    ]

