# Generated by Django 5.2.14 on 2026-05-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_category_eventanalytics_eventimage_payment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_city_222640_idx',
        ),
    ]
